app:
  port: 28091
  secret_key: "oWjbDf6vDOwJQEoAxDXoDulPLdaFKPpdVKu2psBaaT9yugovFN6bSL"
  cors_origins:
    - "*"

mysql:
  username: "root"
  password: "123456"
  host: "127.0.0.1"
  port: "3306"
  dbname: "golang_backend"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "60s"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0
