app:
  port: 8099
  secret_key: "oWjbDf6vDOwJQEoAxDXoDulPLdaFKPpdVKu2psBaaT9yugovFN6bSL"
  cors_origins:
    - "*"

mysql:
  username: "root"
  password: "123456"
  host: "mysql"
  port: "3306"
  dbname: "golang_backend"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "60s"

redis:
  host: "redis"
  port: "6379"
  password: "123456"
  db: 0
