app:
  port: 28091
  secret_key: "oWjbDf6vDOwJQEoAxDXoDulPLdaFKPpdVKu2psBaaT9yugovFN6bSL"
  cors_origins:
    - "*"

database:
  mysql:
    username: "root"
    password: "123456"
    host: "127.0.0.1"
    port: 3306
    dbname: "innoversepm"
    max_open_conns: 50
    max_idle_conns: 10
    conn_max_lifetime: "60s"

  design_gpt_mysql:
    username: "innoverse"
    password: "Innoverse012"
    host: "62.234.73.208"
    port: 13306
    dbname: "innoverse_v3_backend"
    max_open_conns: 50
    max_idle_conns: 10
    conn_max_lifetime: "60s"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

design_gpt_api:
  base_url: "http://62.234.73.208:8008/api/v1"