app:
  port: 28091
  secret_key: "svtzBp1PwHAwJgwttBWZLofYvfMENlepjBuJanzTQwOic0bZLMC7NC"
  cors_origins:
    - "*"

mysql:
  username: "root"
  password: "F4ASxTobZXY4"
  host: "47.106.139.247"
  port: "23306"
  dbname: "golang_backend"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "60s"

redis:
  host: "47.106.139.247"
  port: "26379"
  password: ""
  db: 0
