app:
  port: 28091
  secret_key: "oWjbDf6vDOwJQEoAxDXoDulPLdaFKPpdVKu2psBaaT9yugovFN6bSL"
  cors_origins:
    - "*"

mysql:
  username: "root"
  password: "F4ASxTobZXY4"
  host: "62.234.73.208"
  port: 23306
  dbname: "golang_backend"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "60s"

redis:
  host: "62.234.73.208"
  port: 26379
  password: ""
  db: 1
